select productname,quantityperunit from product;
select productid,productname from product where discontinued = false order by productname;
select productid,productname from product where discontinued = 1 order by productName;
select productname,unitprice from product order by unitPrice desc;
select productid,productname,unitprice from product where unitPrice < 20 and discontinued = false order by unitPrice desc;
select productid,productname,unitprice from product where unitPrice >=15 and unitPrice <=25 and discontinued = false order by unitPrice desc;
select distinct productname,unitprice from product where unitPrice > (select avg(unitPrice) from product) order by unitprice;
select unitprice from product order by unitPrice limit 1 offset 1; 
select productName, unitprice from product order by productName limit 10;
select count(productName) from product group by discontinued;
select productName,unitsonorder,unitsinstock from product where discontinued and unitsInStock < unitsOnOrder;